sudo: required

language: python

services:
  - docker

cache:
  directories:
  - /var/lib/docker/
  - $HOME/.cache/pip

before_install:
  - pip install -r requirements.txt
  - bash -c 'cd docker && docker build --tag=lang-box/java .'

script:
  - python app_tests.py
